openapi: 3.1.1
info:
  version: 2025.10.21
  title: 'Test API'
servers:
  - url: 'https://sandbox.example.com'
    description: Sandbox
  - url: 'https://production.example.com'
    description: Production
paths:
  /foobar:
    post:
      servers:
        - url: 'https://foobar.example.com'
          description: FOOBAR
      tags:
        - Foobar
      summary: Foobar
      description: |
        Foobar
      operationId: post-foobar
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - foo
                - bar
                - baz
              properties:
                foo:
                  description: foo.
                  type: string
                  example: foo
                bar:
                  type: string
                  description: bar.
                  example: bar
                baz:
                  type: string
                  description: baz.
                  example: baz
            examples:
              FOO:
                value:
                  foo: FOOOO
                  bar: FOOOO
                  baz: FOOOO
              BAR:
                value:
                  foo: BAAAAR
                  bar: BAAAAR
                  baz: BAAAAR
              BAZ:
                value:
                  foo: BZZZZZZ
                  bar: BZZZZZZ
                  baz: BZZZZZZ
              QUX:
                value:
                  foo: QuuuuuuuuuuuX
                  bar: QuuuuuuuuuuuX
                  baz: QuuuuuuuuuuuX
      responses:
        '200':
          description: |
            **OK** - Successful foobar attempt, returning a foobar.
          content:
            application/json:
              schema:
                type: object
                required:
                  - foo
                properties:
                  foo:
                    type: string
                    description: foo.
      security: []
